# Generated by Django 4.0.6 on 2022-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_phone_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
